import {saveFile} from '@snickbit/node-utilities'
import {$out, getImportString, getStringContent, initConfig, parseIcon, saveConfig} from '../utilities/common'
import mkdirp from 'mkdirp'
import path from 'path'

export default async function() {
	let config = await initConfig()
	let content = []
	let icons = []
	let aliases = {}

	async function processIcon(raw_icon_name) {
		// get the icon object
		let icon = parseIcon(raw_icon_name)

		// if we've already included it, just return the icon
		if (icons.includes(icon)) {
			return icon
		}

		let import_string = getImportString(icon)

		// if we have a valid import_string, include the icon and return it
		if (import_string) {
			content.push(import_string)
			icons.push(icon)
			return icon
		}

		// if we make it this far, the icon has been skipped
		return false
	}

	for (let raw_icon_name of config.icons) {
		await processIcon(raw_icon_name)
	}

	for (let [alias, resolved_icon] of Object.entries(config.aliases)) {
		let matching_icons = icons.filter(icon => icon.name === resolved_icon || icon.id === resolved_icon)

		let icon = null

		if (matching_icons.length === 1) {
			icon = matching_icons.pop()
		} else {
			icon = await processIcon(resolved_icon)
		}
		if (icon) {
			aliases[alias] = icon.id
		}
	}

	let alias_count = Object.keys(aliases).length

	if (icons.length) {
		content.push(`library.add(${icons.map(icn => icn.prefixed_name).join(', ')})`)
	}

	if (content.length) {
		const ext = config.typescript ? 'ts' : 'js'
		const boot_path = config.output || config.isQuasar ? `src/boot/fontawesome.${ext}` : `src/fontawesome.${ext}`
		let contentString = getStringContent(content, config)

		mkdirp.sync(path.dirname(boot_path))
		saveFile(boot_path, `// DO NOT EDIT - This file is automatically generated\n${contentString}`)
		const newConfig = {
			...config,
			icons: icons.map(icn => icn.id),
			aliases
		}

		if (JSON.stringify(newConfig) !== JSON.stringify(config)) {
			saveConfig(config)
		}
	}

	$out.broken.success('FontAwesome Icons Generated!', `\t${icons.length} icons`, `\t${alias_count} aliases`)

	if (config.isQuasar) {
		$out.info('Don\'t forget to add \'fontawesome\' to your Quasar boot config!')
	}

	$out.done()
}
